### PR TITLE
Priority Select Element

### PR DESCRIPTION
**Pull request by alexpyoung**
## Information
- **Opened:** 10/31/15
## Requirements
- [[EPIC] Team Priorities/Labels](https://trello.com/c/MOTPIDqo)
## Description of Changes
- Creating initial component
## Issues
- [ ] https://github.com/krossoverintelligence/intelligence-web/issues/292

[Review on Reviewable](https://reviewable.io/reviews/krossoverintelligence/krossover-priority-select/1)

### CODE REVIEW

**Comment by alexpyoung** [comment]
https://github.com/krossoverintelligence/intelligence-web/issues/292

**Comment by d640k** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

<sup>**[src/directive.js, line 4 \[r1\]](https://reviewable.io:443/reviews/krossoverintelligence/krossover-priority-select/1#-K1zJtxmjRWSmac4ZcoB)** ([raw file](https://github.com/krossoverintelligence/krossover-priority-select/blob/91545a3d569dc8143f05704d097d6dbe40a3320e/src/directive.js#L4)):</sup>
Why ```new```? I understand the method that returns a fresh string each time, but does ```new``` give you anything? Since it's not a class, the function acts as an ES5 style constructor and is subject to slopping ```this``` references.


---

<sup>**[src/index.js, line 5 \[r1\]](https://reviewable.io:443/reviews/krossoverintelligence/krossover-priority-select/1#-K1zJhCcDCgb4tEDa4kN)** ([raw file](https://github.com/krossoverintelligence/krossover-priority-select/blob/91545a3d569dc8143f05704d097d6dbe40a3320e/src/index.js#L5)):</sup>
This seems a little verbose and makes the code a little less clear. Since the index files are just basically config files, perhaps we don't need any logic in here.


---

<sup>**[src/template.html.js, line 16 \[r1\]](https://reviewable.io:443/reviews/krossoverintelligence/krossover-priority-select/1#-K1zJPylpVhnExER_DQm)** ([raw file](https://github.com/krossoverintelligence/krossover-priority-select/blob/91545a3d569dc8143f05704d097d6dbe40a3320e/src/template.html.js#L16)):</sup>
I guess this would necessitate the need for the color in the data modeling. But, if we just added a class or directive attribute with ```priorityOption.value```, we could use CSS instead.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/krossoverintelligence/krossover-priority-select/1)

**Comment by alexpyoung** [comment]
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

<sup>**[src/directive.js, line 4 \[r1\]](https://reviewable.io:443/reviews/krossoverintelligence/krossover-priority-select/1#-K1zJtxmjRWSmac4ZcoB)** ([raw file](https://github.com/krossoverintelligence/krossover-priority-select/blob/91545a3d569dc8143f05704d097d6dbe40a3320e/src/directive.js#L4)):</sup>
You're right. Removed


---

<sup>**[src/index.js, line 5 \[r1\]](https://reviewable.io:443/reviews/krossoverintelligence/krossover-priority-select/1#-K1zJhCcDCgb4tEDa4kN)** ([raw file](https://github.com/krossoverintelligence/krossover-priority-select/blob/91545a3d569dc8143f05704d097d6dbe40a3320e/src/index.js#L5)):</sup>
Done.


---

<sup>**[src/template.html.js, line 16 \[r1\]](https://reviewable.io:443/reviews/krossoverintelligence/krossover-priority-select/1#-K1zJPylpVhnExER_DQm)** ([raw file](https://github.com/krossoverintelligence/krossover-priority-select/blob/91545a3d569dc8143f05704d097d6dbe40a3320e/src/template.html.js#L16)):</sup>
We already have this component to use though


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/krossoverintelligence/krossover-priority-select/1)

**Comment by d640k** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[src/template.html.js, line 16 \[r1\]](https://reviewable.io:443/reviews/krossoverintelligence/krossover-priority-select/1#-K1zJPylpVhnExER_DQm)** ([raw file](https://github.com/krossoverintelligence/krossover-priority-select/blob/91545a3d569dc8143f05704d097d6dbe40a3320e/src/template.html.js#L16)):</sup>
I'm not sure that's a strong enough argument to use this directive. I understand the value in having this for things like teams, where the color comes from the data, but in this case, we're keeping theme info inside our data models.

Also, a color square inline with text can be implemented trivially in CSS:

```CSS
.high-priority {

    &::before {

        content: "";
        display: inline-block;
        width: @font-size-base;
        height: @font-size-base;
        background-color: @high-priority-color;
        border: 1px solid black;
    }
}
```

We could even go further and create a LESS mixin that creates squares on elements with color and size as parameters.

This would also clean up your markup:

```HTML
<span
    ng-class="{'high-priority': priorityOption.id === PRIORITIES.HIGH}"
>{{priorityOption.name}}</span>
```


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/krossoverintelligence/krossover-priority-select/1)

**Pull request closed without merging**
